export const LANGUE_PAR_DEFAUT = 'fr'

export const TRADUCTIONS = {
  fr: {
    app_titre: 'StockResto',
    nav_stock: 'Stock',
    nav_vendre: 'Vendre un plat',
    nav_nouvel_ingredient: 'Nouvel ingrédient',
    nav_nouveau_plat: 'Nouveau plat',
    nav_nouvelle_recette: 'Nouvelle recette',
    nav_historique: 'Historique',
    nav_fournisseurs: 'Fournisseurs',
    nav_statistiques: 'Statistiques',

    chargement: 'Chargement...',
    erreur_chargement: 'Erreur de chargement',
    erreur_prefixe: 'Erreur :',
    unite_piece: 'unité',
    bouton_ajout_en_cours: 'Ajout en cours...',
    label_nom: 'Nom',
    label_unite: 'Unité',
    colonne_stock_actuel: 'Stock actuel',
    colonne_seuil_minimum: 'Seuil minimum',

    titre_page_stock: 'Stock des ingrédients - StockResto',
    titre_stock: 'Ingrédients en stock',
    colonne_ingredient: 'Ingrédient',
    colonne_statut: 'Statut',
    statut_ok: 'OK',
    statut_bas: 'Bas',
    statut_critique: 'Critique',
    erreur_chargement_stock: 'Erreur de chargement :',
    colonne_actions: 'Actions',
    titre_ajouter_stock: 'Ajouter du stock',
    titre_retirer_stock: 'Retirer du stock',
    bouton_annuler: 'Annuler',
    bouton_confirmer: 'Confirmer',
    bouton_confirmation_en_cours: 'Confirmation en cours...',
    erreur_stock_negatif: 'Stock insuffisant : {ingredient} n’a que {stock} {unite} en stock.',
    bouton_modifier: 'Modifier',
    bouton_supprimer: 'Supprimer',
    bouton_fermer: 'Fermer',
    bouton_enregistrer: 'Enregistrer',
    bouton_enregistrement_en_cours: 'Enregistrement en cours...',
    titre_modifier_ingredient: "Modifier l'ingrédient",
    titre_supprimer_ingredient: "Supprimer l'ingrédient",
    verification_en_cours: 'Vérification en cours...',
    confirmation_suppression: 'Êtes-vous sûr de vouloir supprimer {ingredient} ?',
    erreur_ingredient_utilise: 'Impossible de supprimer {ingredient} : utilisé dans la recette de {plats}.',
    suppression_en_cours: 'Suppression en cours...',

    titre_page_vendre: 'Vendre un plat - StockResto',
    titre_vendre: 'Vendre un plat',
    label_plat: 'Plat',
    chargement_plats: 'Chargement des plats...',
    bouton_vendre: 'Vendre',
    bouton_vente_en_cours: 'Vente en cours...',
    vente_enregistree: 'Vente enregistrée',
    erreur_recette_introuvable: 'Aucune recette trouvée pour ce plat.',
    alerte_stock_bas: 'Stock bas : {ingredient}',
    alerte_erreur_ingredient: 'Erreur en cherchant un ingrédient : {message}',
    alerte_erreur_stock: 'Erreur en mettant à jour {ingredient} : {message}',
    lien_voir_detail: 'Voir le détail',
    lien_masquer_detail: 'Masquer le détail',

    titre_page_nouvel_ingredient: 'Nouvel ingrédient - StockResto',
    titre_nouvel_ingredient: 'Ajouter un ingrédient',
    label_prix_achat: "Prix d'achat (DH)",
    bouton_ajouter_ingredient: "Ajouter l'ingrédient",
    ingredient_ajoute: 'Ingrédient "{nom}" ajouté avec succès.',

    titre_page_nouveau_plat: 'Nouveau plat - StockResto',
    titre_nouveau_plat: 'Ajouter un plat',
    label_categorie: 'Catégorie',
    label_nouvelle_categorie: 'Nouvelle catégorie',
    label_prix_vente: 'Prix de vente (DH)',
    chargement_categories: 'Chargement des catégories...',
    option_nouvelle_categorie: '+ Nouvelle catégorie...',
    bouton_ajouter_plat: 'Ajouter le plat',
    plat_ajoute: 'Plat "{nom}" ajouté avec succès.',
    titre_plats_existants: 'Plats existants',
    titre_modifier_plat: 'Modifier le plat',
    titre_supprimer_plat: 'Supprimer le plat',
    erreur_plat_utilise: "{plat} a une recette associée : supprimez d'abord la recette.",
    confirmation_suppression_plat: 'Êtes-vous sûr de vouloir supprimer {plat} ?',

    titre_page_nouvelle_recette: 'Nouvelle recette - StockResto',
    titre_nouvelle_recette: 'Associer un ingrédient à un plat',
    label_ingredient: 'Ingrédient',
    label_quantite: 'Quantité',
    chargement_ingredients: 'Chargement des ingrédients...',
    bouton_ajouter_recette: 'Ajouter à la recette',
    recette_ajoutee: 'Ingrédient ajouté à la recette.',
    titre_recettes_existantes: 'Recettes existantes',
    colonne_ingredients: 'Ingrédients',
    titre_modifier_recette: 'Modifier la recette',
    titre_supprimer_recette: 'Supprimer la recette',
    bouton_ajouter_ligne: '+ Ajouter un ingrédient',
    confirmation_suppression_recette: 'Êtes-vous sûr de vouloir supprimer la recette de {plat} ?',
    erreur_ligne_recette_invalide: 'Chaque ligne doit avoir un ingrédient et une quantité supérieure à 0.',

    titre_page_historique: 'Historique - StockResto',
    titre_historique: 'Historique des mouvements',
    colonne_date: 'Date/Heure',
    colonne_motif: 'Motif',
    motif_ajout: 'Ajout',
    motif_retrait: 'Retrait',
    motif_vente: 'Vente',
    bouton_charger_plus: 'Charger plus',

    titre_page_nouveau_fournisseur: 'Nouveau fournisseur - StockResto',
    titre_nouveau_fournisseur: 'Ajouter un fournisseur',
    label_contact: 'Téléphone',
    label_produits: 'Produits',
    bouton_ajouter_fournisseur: 'Ajouter le fournisseur',
    fournisseur_ajoute: 'Fournisseur "{nom}" ajouté avec succès.',
    titre_fournisseurs_existants: 'Fournisseurs existants',
    titre_modifier_fournisseur: 'Modifier le fournisseur',
    titre_supprimer_fournisseur: 'Supprimer le fournisseur',
    confirmation_suppression_fournisseur: 'Êtes-vous sûr de vouloir supprimer {fournisseur} ?',

    titre_page_statistiques: 'Statistiques - StockResto',
    titre_plats_plus_vendus: 'Plats les plus vendus (30 derniers jours)',
    colonne_nombre_ventes: 'Ventes',
    titre_cout_plats: 'Coût des plats',
    colonne_cout: 'Coût (DH)',
    colonne_marge: 'Marge (DH)',
    titre_ingredients_alerte: 'Ingrédients en alerte',
    aucune_donnee: 'Aucune donnée pour le moment.',
    aucune_alerte: 'Aucun ingrédient en alerte.',
  },

  en: {
    app_titre: 'StockResto',
    nav_stock: 'Stock',
    nav_vendre: 'Sell a Dish',
    nav_nouvel_ingredient: 'New Ingredient',
    nav_nouveau_plat: 'New Dish',
    nav_nouvelle_recette: 'New Recipe',
    nav_historique: 'History',
    nav_fournisseurs: 'Suppliers',
    nav_statistiques: 'Statistics',

    chargement: 'Loading...',
    erreur_chargement: 'Loading error',
    erreur_prefixe: 'Error:',
    unite_piece: 'unit',
    bouton_ajout_en_cours: 'Adding...',
    label_nom: 'Name',
    label_unite: 'Unit',
    colonne_stock_actuel: 'Current Stock',
    colonne_seuil_minimum: 'Minimum Threshold',

    titre_page_stock: 'Stock - StockResto',
    titre_stock: 'Ingredients in Stock',
    colonne_ingredient: 'Ingredient',
    colonne_statut: 'Status',
    statut_ok: 'OK',
    statut_bas: 'Low',
    statut_critique: 'Critical',
    erreur_chargement_stock: 'Loading error:',
    colonne_actions: 'Actions',
    titre_ajouter_stock: 'Add Stock',
    titre_retirer_stock: 'Remove Stock',
    bouton_annuler: 'Cancel',
    bouton_confirmer: 'Confirm',
    bouton_confirmation_en_cours: 'Confirming...',
    erreur_stock_negatif: 'Insufficient stock: {ingredient} only has {stock} {unite} in stock.',
    bouton_modifier: 'Edit',
    bouton_supprimer: 'Delete',
    bouton_fermer: 'Close',
    bouton_enregistrer: 'Save',
    bouton_enregistrement_en_cours: 'Saving...',
    titre_modifier_ingredient: 'Edit Ingredient',
    titre_supprimer_ingredient: 'Delete Ingredient',
    verification_en_cours: 'Checking...',
    confirmation_suppression: 'Are you sure you want to delete {ingredient}?',
    erreur_ingredient_utilise: 'Cannot delete {ingredient}: used in the recipe for {plats}.',
    suppression_en_cours: 'Deleting...',

    titre_page_vendre: 'Sell a Dish - StockResto',
    titre_vendre: 'Sell a Dish',
    label_plat: 'Dish',
    chargement_plats: 'Loading dishes...',
    bouton_vendre: 'Sell',
    bouton_vente_en_cours: 'Selling...',
    vente_enregistree: 'Sale recorded',
    erreur_recette_introuvable: 'No recipe found for this dish.',
    alerte_stock_bas: 'Low stock: {ingredient}',
    alerte_erreur_ingredient: 'Error looking up an ingredient: {message}',
    alerte_erreur_stock: 'Error updating {ingredient}: {message}',
    lien_voir_detail: 'View details',
    lien_masquer_detail: 'Hide details',

    titre_page_nouvel_ingredient: 'New Ingredient - StockResto',
    titre_nouvel_ingredient: 'Add an Ingredient',
    label_prix_achat: 'Purchase Price (DH)',
    bouton_ajouter_ingredient: 'Add Ingredient',
    ingredient_ajoute: 'Ingredient "{nom}" added successfully.',

    titre_page_nouveau_plat: 'New Dish - StockResto',
    titre_nouveau_plat: 'Add a Dish',
    label_categorie: 'Category',
    label_nouvelle_categorie: 'New Category',
    label_prix_vente: 'Selling Price (DH)',
    chargement_categories: 'Loading categories...',
    option_nouvelle_categorie: '+ New category...',
    bouton_ajouter_plat: 'Add Dish',
    plat_ajoute: 'Dish "{nom}" added successfully.',
    titre_plats_existants: 'Existing Dishes',
    titre_modifier_plat: 'Edit Dish',
    titre_supprimer_plat: 'Delete Dish',
    erreur_plat_utilise: '{plat} has an associated recipe: remove the recipe first.',
    confirmation_suppression_plat: 'Are you sure you want to delete {plat}?',

    titre_page_nouvelle_recette: 'New Recipe - StockResto',
    titre_nouvelle_recette: 'Link an Ingredient to a Dish',
    label_ingredient: 'Ingredient',
    label_quantite: 'Quantity',
    chargement_ingredients: 'Loading ingredients...',
    bouton_ajouter_recette: 'Add to Recipe',
    recette_ajoutee: 'Ingredient added to the recipe.',
    titre_recettes_existantes: 'Existing Recipes',
    colonne_ingredients: 'Ingredients',
    titre_modifier_recette: 'Edit Recipe',
    titre_supprimer_recette: 'Delete Recipe',
    bouton_ajouter_ligne: '+ Add an ingredient',
    confirmation_suppression_recette: 'Are you sure you want to delete the recipe for {plat}?',
    erreur_ligne_recette_invalide: 'Each line must have an ingredient and a quantity greater than 0.',

    titre_page_historique: 'History - StockResto',
    titre_historique: 'Movement History',
    colonne_date: 'Date/Time',
    colonne_motif: 'Reason',
    motif_ajout: 'Added',
    motif_retrait: 'Removed',
    motif_vente: 'Sale',
    bouton_charger_plus: 'Load more',

    titre_page_nouveau_fournisseur: 'New Supplier - StockResto',
    titre_nouveau_fournisseur: 'Add a Supplier',
    label_contact: 'Phone',
    label_produits: 'Products',
    bouton_ajouter_fournisseur: 'Add Supplier',
    fournisseur_ajoute: 'Supplier "{nom}" added successfully.',
    titre_fournisseurs_existants: 'Existing Suppliers',
    titre_modifier_fournisseur: 'Edit Supplier',
    titre_supprimer_fournisseur: 'Delete Supplier',
    confirmation_suppression_fournisseur: 'Are you sure you want to delete {fournisseur}?',

    titre_page_statistiques: 'Statistics - StockResto',
    titre_plats_plus_vendus: 'Best-Selling Dishes (last 30 days)',
    colonne_nombre_ventes: 'Sales',
    titre_cout_plats: 'Dish Costs',
    colonne_cout: 'Cost (DH)',
    colonne_marge: 'Margin (DH)',
    titre_ingredients_alerte: 'Ingredients on Alert',
    aucune_donnee: 'No data yet.',
    aucune_alerte: 'No ingredients on alert.',
  },

  es: {
    app_titre: 'StockResto',
    nav_stock: 'Stock',
    nav_vendre: 'Vender un Plato',
    nav_nouvel_ingredient: 'Nuevo Ingrediente',
    nav_nouveau_plat: 'Nuevo Plato',
    nav_nouvelle_recette: 'Nueva Receta',
    nav_historique: 'Historial',
    nav_fournisseurs: 'Proveedores',
    nav_statistiques: 'Estadísticas',

    chargement: 'Cargando...',
    erreur_chargement: 'Error de carga',
    erreur_prefixe: 'Error:',
    unite_piece: 'unidad',
    bouton_ajout_en_cours: 'Añadiendo...',
    label_nom: 'Nombre',
    label_unite: 'Unidad',
    colonne_stock_actuel: 'Stock Actual',
    colonne_seuil_minimum: 'Umbral Mínimo',

    titre_page_stock: 'Stock - StockResto',
    titre_stock: 'Ingredientes en Stock',
    colonne_ingredient: 'Ingrediente',
    colonne_statut: 'Estado',
    statut_ok: 'OK',
    statut_bas: 'Bajo',
    statut_critique: 'Crítico',
    erreur_chargement_stock: 'Error de carga:',
    colonne_actions: 'Acciones',
    titre_ajouter_stock: 'Añadir Stock',
    titre_retirer_stock: 'Quitar Stock',
    bouton_annuler: 'Cancelar',
    bouton_confirmer: 'Confirmar',
    bouton_confirmation_en_cours: 'Confirmando...',
    erreur_stock_negatif: 'Stock insuficiente: {ingredient} solo tiene {stock} {unite} en stock.',
    bouton_modifier: 'Editar',
    bouton_supprimer: 'Eliminar',
    bouton_fermer: 'Cerrar',
    bouton_enregistrer: 'Guardar',
    bouton_enregistrement_en_cours: 'Guardando...',
    titre_modifier_ingredient: 'Editar Ingrediente',
    titre_supprimer_ingredient: 'Eliminar Ingrediente',
    verification_en_cours: 'Verificando...',
    confirmation_suppression: '¿Seguro que quieres eliminar {ingredient}?',
    erreur_ingredient_utilise: 'No se puede eliminar {ingredient}: se usa en la receta de {plats}.',
    suppression_en_cours: 'Eliminando...',

    titre_page_vendre: 'Vender un Plato - StockResto',
    titre_vendre: 'Vender un Plato',
    label_plat: 'Plato',
    chargement_plats: 'Cargando platos...',
    bouton_vendre: 'Vender',
    bouton_vente_en_cours: 'Vendiendo...',
    vente_enregistree: 'Venta registrada',
    erreur_recette_introuvable: 'No se encontró receta para este plato.',
    alerte_stock_bas: 'Stock bajo: {ingredient}',
    alerte_erreur_ingredient: 'Error al buscar un ingrediente: {message}',
    alerte_erreur_stock: 'Error al actualizar {ingredient}: {message}',
    lien_voir_detail: 'Ver detalle',
    lien_masquer_detail: 'Ocultar detalle',

    titre_page_nouvel_ingredient: 'Nuevo Ingrediente - StockResto',
    titre_nouvel_ingredient: 'Añadir un Ingrediente',
    label_prix_achat: 'Precio de Compra (DH)',
    bouton_ajouter_ingredient: 'Añadir Ingrediente',
    ingredient_ajoute: 'Ingrediente "{nom}" añadido con éxito.',

    titre_page_nouveau_plat: 'Nuevo Plato - StockResto',
    titre_nouveau_plat: 'Añadir un Plato',
    label_categorie: 'Categoría',
    label_nouvelle_categorie: 'Nueva Categoría',
    label_prix_vente: 'Precio de Venta (DH)',
    chargement_categories: 'Cargando categorías...',
    option_nouvelle_categorie: '+ Nueva categoría...',
    bouton_ajouter_plat: 'Añadir Plato',
    plat_ajoute: 'Plato "{nom}" añadido con éxito.',
    titre_plats_existants: 'Platos Existentes',
    titre_modifier_plat: 'Editar Plato',
    titre_supprimer_plat: 'Eliminar Plato',
    erreur_plat_utilise: '{plat} tiene una receta asociada: elimina primero la receta.',
    confirmation_suppression_plat: '¿Seguro que quieres eliminar {plat}?',

    titre_page_nouvelle_recette: 'Nueva Receta - StockResto',
    titre_nouvelle_recette: 'Asociar un Ingrediente a un Plato',
    label_ingredient: 'Ingrediente',
    label_quantite: 'Cantidad',
    chargement_ingredients: 'Cargando ingredientes...',
    bouton_ajouter_recette: 'Añadir a la Receta',
    recette_ajoutee: 'Ingrediente añadido a la receta.',
    titre_recettes_existantes: 'Recetas Existentes',
    colonne_ingredients: 'Ingredientes',
    titre_modifier_recette: 'Editar Receta',
    titre_supprimer_recette: 'Eliminar Receta',
    bouton_ajouter_ligne: '+ Añadir un ingrediente',
    confirmation_suppression_recette: '¿Seguro que quieres eliminar la receta de {plat}?',
    erreur_ligne_recette_invalide: 'Cada línea debe tener un ingrediente y una cantidad mayor que 0.',

    titre_page_historique: 'Historial - StockResto',
    titre_historique: 'Historial de Movimientos',
    colonne_date: 'Fecha/Hora',
    colonne_motif: 'Motivo',
    motif_ajout: 'Añadido',
    motif_retrait: 'Retirado',
    motif_vente: 'Venta',
    bouton_charger_plus: 'Cargar más',

    titre_page_nouveau_fournisseur: 'Nuevo Proveedor - StockResto',
    titre_nouveau_fournisseur: 'Añadir un Proveedor',
    label_contact: 'Teléfono',
    label_produits: 'Productos',
    bouton_ajouter_fournisseur: 'Añadir Proveedor',
    fournisseur_ajoute: 'Proveedor "{nom}" añadido con éxito.',
    titre_fournisseurs_existants: 'Proveedores Existentes',
    titre_modifier_fournisseur: 'Editar Proveedor',
    titre_supprimer_fournisseur: 'Eliminar Proveedor',
    confirmation_suppression_fournisseur: '¿Seguro que quieres eliminar {fournisseur}?',

    titre_page_statistiques: 'Estadísticas - StockResto',
    titre_plats_plus_vendus: 'Platos Más Vendidos (últimos 30 días)',
    colonne_nombre_ventes: 'Ventas',
    titre_cout_plats: 'Costo de los Platos',
    colonne_cout: 'Costo (DH)',
    colonne_marge: 'Margen (DH)',
    titre_ingredients_alerte: 'Ingredientes en Alerta',
    aucune_donnee: 'Sin datos por el momento.',
    aucune_alerte: 'Ningún ingrediente en alerta.',
  },

  ar: {
    app_titre: 'StockResto',
    nav_stock: 'المخزون',
    nav_vendre: 'بيع طبق',
    nav_nouvel_ingredient: 'مكوّن جديد',
    nav_nouveau_plat: 'طبق جديد',
    nav_nouvelle_recette: 'وصفة جديدة',
    nav_historique: 'السجل',
    nav_fournisseurs: 'الموردون',
    nav_statistiques: 'الإحصائيات',

    chargement: 'جارٍ التحميل...',
    erreur_chargement: 'خطأ في التحميل',
    erreur_prefixe: 'خطأ:',
    unite_piece: 'وحدة',
    bouton_ajout_en_cours: 'جارٍ الإضافة...',
    label_nom: 'الاسم',
    label_unite: 'الوحدة',
    colonne_stock_actuel: 'المخزون الحالي',
    colonne_seuil_minimum: 'الحد الأدنى',

    titre_page_stock: 'المخزون - StockResto',
    titre_stock: 'المكونات في المخزون',
    colonne_ingredient: 'المكوّن',
    colonne_statut: 'الحالة',
    statut_ok: 'جيد',
    statut_bas: 'منخفض',
    statut_critique: 'حرج',
    erreur_chargement_stock: 'خطأ في التحميل:',
    colonne_actions: 'إجراءات',
    titre_ajouter_stock: 'إضافة مخزون',
    titre_retirer_stock: 'خصم مخزون',
    bouton_annuler: 'إلغاء',
    bouton_confirmer: 'تأكيد',
    bouton_confirmation_en_cours: 'جارٍ التأكيد...',
    erreur_stock_negatif: 'المخزون غير كافٍ: {ingredient} لا يملك سوى {stock} {unite} في المخزون.',
    bouton_modifier: 'تعديل',
    bouton_supprimer: 'حذف',
    bouton_fermer: 'إغلاق',
    bouton_enregistrer: 'حفظ',
    bouton_enregistrement_en_cours: 'جارٍ الحفظ...',
    titre_modifier_ingredient: 'تعديل المكوّن',
    titre_supprimer_ingredient: 'حذف المكوّن',
    verification_en_cours: 'جارٍ التحقق...',
    confirmation_suppression: 'هل أنت متأكد من حذف {ingredient}؟',
    erreur_ingredient_utilise: 'لا يمكن حذف {ingredient}: مستخدم في وصفة {plats}.',
    suppression_en_cours: 'جارٍ الحذف...',

    titre_page_vendre: 'بيع طبق - StockResto',
    titre_vendre: 'بيع طبق',
    label_plat: 'الطبق',
    chargement_plats: 'جارٍ تحميل الأطباق...',
    bouton_vendre: 'بيع',
    bouton_vente_en_cours: 'جارٍ البيع...',
    vente_enregistree: 'تم تسجيل البيع',
    erreur_recette_introuvable: 'لم يتم العثور على وصفة لهذا الطبق.',
    alerte_stock_bas: 'مخزون منخفض: {ingredient}',
    alerte_erreur_ingredient: 'خطأ في البحث عن مكوّن: {message}',
    alerte_erreur_stock: 'خطأ في تحديث {ingredient}: {message}',
    lien_voir_detail: 'عرض التفاصيل',
    lien_masquer_detail: 'إخفاء التفاصيل',

    titre_page_nouvel_ingredient: 'مكوّن جديد - StockResto',
    titre_nouvel_ingredient: 'إضافة مكوّن',
    label_prix_achat: 'سعر الشراء (درهم)',
    bouton_ajouter_ingredient: 'إضافة المكوّن',
    ingredient_ajoute: 'تمت إضافة المكوّن "{nom}" بنجاح.',

    titre_page_nouveau_plat: 'طبق جديد - StockResto',
    titre_nouveau_plat: 'إضافة طبق',
    label_categorie: 'الفئة',
    label_nouvelle_categorie: 'فئة جديدة',
    label_prix_vente: 'سعر البيع (درهم)',
    chargement_categories: 'جارٍ تحميل الفئات...',
    option_nouvelle_categorie: '+ فئة جديدة...',
    bouton_ajouter_plat: 'إضافة الطبق',
    plat_ajoute: 'تمت إضافة الطبق "{nom}" بنجاح.',
    titre_plats_existants: 'الأطباق الموجودة',
    titre_modifier_plat: 'تعديل الطبق',
    titre_supprimer_plat: 'حذف الطبق',
    erreur_plat_utilise: '{plat} لديه وصفة مرتبطة: احذف الوصفة أولاً.',
    confirmation_suppression_plat: 'هل أنت متأكد من حذف {plat}؟',

    titre_page_nouvelle_recette: 'وصفة جديدة - StockResto',
    titre_nouvelle_recette: 'ربط مكوّن بطبق',
    label_ingredient: 'المكوّن',
    label_quantite: 'الكمية',
    chargement_ingredients: 'جارٍ تحميل المكوّنات...',
    bouton_ajouter_recette: 'إضافة إلى الوصفة',
    recette_ajoutee: 'تمت إضافة المكوّن إلى الوصفة.',
    titre_recettes_existantes: 'الوصفات الموجودة',
    colonne_ingredients: 'المكوّنات',
    titre_modifier_recette: 'تعديل الوصفة',
    titre_supprimer_recette: 'حذف الوصفة',
    bouton_ajouter_ligne: '+ إضافة مكوّن',
    confirmation_suppression_recette: 'هل أنت متأكد من حذف وصفة {plat}؟',
    erreur_ligne_recette_invalide: 'يجب أن يحتوي كل سطر على مكوّن وكمية أكبر من 0.',

    titre_page_historique: 'السجل - StockResto',
    titre_historique: 'سجل الحركات',
    colonne_date: 'التاريخ/الوقت',
    colonne_motif: 'السبب',
    motif_ajout: 'إضافة',
    motif_retrait: 'سحب',
    motif_vente: 'بيع',
    bouton_charger_plus: 'تحميل المزيد',

    titre_page_nouveau_fournisseur: 'مورد جديد - StockResto',
    titre_nouveau_fournisseur: 'إضافة مورد',
    label_contact: 'الهاتف',
    label_produits: 'المنتجات',
    bouton_ajouter_fournisseur: 'إضافة المورد',
    fournisseur_ajoute: 'تمت إضافة المورد "{nom}" بنجاح.',
    titre_fournisseurs_existants: 'الموردون الحاليون',
    titre_modifier_fournisseur: 'تعديل المورد',
    titre_supprimer_fournisseur: 'حذف المورد',
    confirmation_suppression_fournisseur: 'هل أنت متأكد من حذف {fournisseur}؟',

    titre_page_statistiques: 'الإحصائيات - StockResto',
    titre_plats_plus_vendus: 'الأطباق الأكثر مبيعًا (آخر 30 يومًا)',
    colonne_nombre_ventes: 'المبيعات',
    titre_cout_plats: 'تكلفة الأطباق',
    colonne_cout: 'التكلفة (درهم)',
    colonne_marge: 'الهامش (درهم)',
    titre_ingredients_alerte: 'مكوّنات في حالة تنبيه',
    aucune_donnee: 'لا توجد بيانات حاليًا.',
    aucune_alerte: 'لا يوجد أي مكوّن في حالة تنبيه.',
  },
}
